name: Build

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: chmod +x gradlew && ./gradlew build
      - name: Upload release libs
        uses: actions/upload-artifact@v3
        with:
          name: release-libs
          path: build/libs/*
      - name: Upload dev libs
        uses: actions/upload-artifact@v3
        with:
          name: dev-libs
          path: build/devlibs/*
